export enum IconsEnum {
    calendar = 'calendar',
    check_list = 'check_list',
    arrow_back = 'arrow_back',
    dashboard = 'dashboard',
    logout = 'logout',
    settings = 'settings',
    menu = 'menu',
    close = 'close',
    people = 'people',
    style = 'style',
    info = 'info',
    warning = 'warning',
    error = 'error',
    success = 'success',
    refresh = 'refresh',
    tune = 'tune',
}