export enum IconsEnum {
    calendar = 'calendar',
    check_list = 'check_list',
    arrow_back = 'arrow_back',
    dashboard = 'dashboard',
    logout = 'logout',
    settings = 'settings',
    menu = 'menu',
    close = 'close',
    people = 'people',
    style = 'style',
    info = 'info',
    warning = 'warning',
    error = 'error',
    success = 'success',
    refresh = 'refresh',
    tune = 'tune',
    edit = 'edit',
    payments = 'payments',
    mongoDB_horizontal = 'brands/mongoDB_horizontal',
    heroku_horizontal = 'brands/heroku_horizontal',
    coralogix_horizontal = 'brands/coralogix_horizontal',
    netlify_horizontal = 'brands/netlify_horizontal'
}